/* Auto-generated by auto_register.py — do not edit */
#include "fabric_init.h"
#include "fabric_register_all.h"
#include "../../../unikraft/lib/fabric-core/backends/include/backends.h"
#include "../../../unikraft/lib/fabric-core/bridge/include/bridge.h"
#include "../../../unikraft/lib/fabric-core/component/include/component.h"
#include "../../../unikraft/lib/fabric-core/controller/include/controller.h"
#include "../../../unikraft/lib/fabric-core/include/fabric_error.h"
#include <flexos/isolation.h>
#include <uk/config.h>
#if CONFIG_LIBFLEXOS_VMEPT
#include <flexos/impl/vmept.h>
#endif
#include <stdio.h>
#include <uk/init.h>
#include <uk/page.h>
#include <uk/prio.h>

int fabric_bridge_bind_downstream(struct FabricBridge *bridge, Fabric *fabric);

Fabric *g_comp1_fabric_1 = (void *)0;
Fabric *g_comp1_fabric_2 = (void *)0;
Fabric *g_comp1_fabric_3 = (void *)0;


static int fabric_bind_bidi(Fabric *left, Fabric *right)
{
    if (!left || !right || !left->bridge || !right->bridge)
        return FABRIC_ERROR;
    if (fabric_bridge_bind_downstream(left->bridge, right) != FABRIC_SUCCESS)
        return FABRIC_ERROR;
    if (fabric_bridge_bind_downstream(right->bridge, left) != FABRIC_SUCCESS)
        return FABRIC_ERROR;
    return FABRIC_SUCCESS;
}

int fabric_init_all(void)
{
    int rc;

    g_comp1_fabric_1 = fabric_create();
    g_comp1_fabric_2 = fabric_create();
    g_comp1_fabric_3 = fabric_create();
    if (!g_comp1_fabric_1 || !g_comp1_fabric_2 || !g_comp1_fabric_3)
        return FABRIC_ERROR;

    struct fabric_lib_binding {
        const char *lib_name;
        Fabric *fabric;
        int (*register_fn)(Fabric *);
    };

    struct fabric_lib_binding bindings[] = {
        { "example2", g_comp1_fabric_2, register_example2_functions },
        { "example3", g_comp1_fabric_3, register_example3_functions },
    };
    int binding_count = (int)(sizeof(bindings) / sizeof(bindings[0]));
    for (int i = 0; i < binding_count; i++) {
        rc = bindings[i].register_fn(bindings[i].fabric);
        if (rc != FABRIC_SUCCESS)
            return rc;
    }

    rc = fabric_bind_bidi(g_comp1_fabric_1, g_comp1_fabric_2);
    if (rc != FABRIC_SUCCESS)
        return rc;
    rc = fabric_bind_bidi(g_comp1_fabric_1, g_comp1_fabric_3);
    if (rc != FABRIC_SUCCESS)
        return rc;

    /* --- 隔离后端初始化 --- */
    {
        EPTConfig iso_cfg;
        iso_cfg.fabric_id = g_comp1_fabric_1->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_1->bridge, FABRIC_ISO_EPT, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_2->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_2->bridge, FABRIC_ISO_EPT, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_3->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_3->bridge, FABRIC_ISO_EPT, &iso_cfg);
    }

    /* --- MPK 内存页面标记 --- */
    {
        extern int flexos_intelpku_mem_set_key(void *, uint64_t, uint8_t);
        extern char _fabric_comp1_fabric_2_data_start[], _fabric_comp1_fabric_2_data_end[];
        extern char _fabric_comp1_fabric_2_bss_start[], _fabric_comp1_fabric_2_bss_end[];
        extern char _fabric_comp1_fabric_2_text_start[], _fabric_comp1_fabric_2_text_end[];
        extern char _fabric_comp1_fabric_3_data_start[], _fabric_comp1_fabric_3_data_end[];
        extern char _fabric_comp1_fabric_3_bss_start[], _fabric_comp1_fabric_3_bss_end[];
        extern char _fabric_comp1_fabric_3_text_start[], _fabric_comp1_fabric_3_text_end[];

        /* tag comp1_fabric-2 sections with fabric key */
        do {
            MPKBridgeState *_st = g_comp1_fabric_2->bridge->iso_state ?
                (MPKBridgeState *)g_comp1_fabric_2->bridge->iso_state : (void *)0;
            uint32_t _key = _st ? _st->my_key : 0;
            printf("[AKIRA-MPK] tagging comp1_fabric-2: iso_state=%p key=%u\n", _st, _key);
            if (_key > 0) {
                uintptr_t _s, _e, _np;
                _s = (uintptr_t)_fabric_comp1_fabric_2_data_start & ~(uintptr_t)0xFFF;
                _e = ((uintptr_t)_fabric_comp1_fabric_2_data_end + 0xFFF) & ~(uintptr_t)0xFFF;
                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;
                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);
                _s = (uintptr_t)_fabric_comp1_fabric_2_bss_start & ~(uintptr_t)0xFFF;
                _e = ((uintptr_t)_fabric_comp1_fabric_2_bss_end + 0xFFF) & ~(uintptr_t)0xFFF;
                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;
                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);
                _s = (uintptr_t)_fabric_comp1_fabric_2_text_start & ~(uintptr_t)0xFFF;
                _e = ((uintptr_t)_fabric_comp1_fabric_2_text_end + 0xFFF) & ~(uintptr_t)0xFFF;
                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;
                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);
                printf("[AKIRA-MPK] tagged fabric comp1_fabric-2 key=%u\n", _key);
            }
        } while (0);
        /* tag comp1_fabric-3 sections with fabric key */
        do {
            MPKBridgeState *_st = g_comp1_fabric_3->bridge->iso_state ?
                (MPKBridgeState *)g_comp1_fabric_3->bridge->iso_state : (void *)0;
            uint32_t _key = _st ? _st->my_key : 0;
            printf("[AKIRA-MPK] tagging comp1_fabric-3: iso_state=%p key=%u\n", _st, _key);
            if (_key > 0) {
                uintptr_t _s, _e, _np;
                _s = (uintptr_t)_fabric_comp1_fabric_3_data_start & ~(uintptr_t)0xFFF;
                _e = ((uintptr_t)_fabric_comp1_fabric_3_data_end + 0xFFF) & ~(uintptr_t)0xFFF;
                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;
                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);
                _s = (uintptr_t)_fabric_comp1_fabric_3_bss_start & ~(uintptr_t)0xFFF;
                _e = ((uintptr_t)_fabric_comp1_fabric_3_bss_end + 0xFFF) & ~(uintptr_t)0xFFF;
                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;
                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);
                _s = (uintptr_t)_fabric_comp1_fabric_3_text_start & ~(uintptr_t)0xFFF;
                _e = ((uintptr_t)_fabric_comp1_fabric_3_text_end + 0xFFF) & ~(uintptr_t)0xFFF;
                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;
                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);
                printf("[AKIRA-MPK] tagged fabric comp1_fabric-3 key=%u\n", _key);
            }
        } while (0);
    }

    return FABRIC_SUCCESS;
}

static int __fabric_lib_init(void)
{
    return fabric_init_all();
}
uk_lib_initcall_prio(__fabric_lib_init, UK_PRIO_EARLIEST);
