/* Auto-generated by auto_register.py — do not edit */
#include "fabric_register_all.h"
#include <uk/print.h>

extern const char __fsym_example2_empty[] __asm__("example2_empty") __attribute__((weak));
extern const char __fsym_example3_empty[] __asm__("example3_empty") __attribute__((weak));

int register_example2_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_example2_empty == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: example2_empty (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "example2_empty", (func_t)(void *)__fsym_example2_empty);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] example2: %d registered, %d missing, 1 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_example3_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_example3_empty == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: example3_empty (example3)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "example3_empty", (func_t)(void *)__fsym_example3_empty);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] example3: %d registered, %d missing, 1 total\n", registered, missing);
    return FABRIC_SUCCESS;
}
