// Auto-generated by auto_register.py — do not edit

// Auto-generated for /root/.unikraft_akira/apps/base-overhead/cross_domain.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example2_empty, EL)
+ fabric_gate(0, example2_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example2_empty, EL)
+ fabric_gate_r(0, RET, example2_empty, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e2c1, EL)
+ fabric_gate(0, e2c1, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e2c1, EL)
+ fabric_gate_r(0, RET, e2c1, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e2c2, EL)
+ fabric_gate(0, e2c2, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e2c2, EL)
+ fabric_gate_r(0, RET, e2c2, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e2c3, EL)
+ fabric_gate(0, e2c3, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e2c3, EL)
+ fabric_gate_r(0, RET, e2c3, EL)

// Auto-generated for /root/.unikraft_akira/apps/base-overhead/cross_domain_re.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example2_empty, EL)
+ fabric_gate(0, example2_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example2_empty, EL)
+ fabric_gate_r(0, RET, example2_empty, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e2c1, EL)
+ fabric_gate(0, e2c1, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e2c1, EL)
+ fabric_gate_r(0, RET, e2c1, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e2c2, EL)
+ fabric_gate(0, e2c2, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e2c2, EL)
+ fabric_gate_r(0, RET, e2c2, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e2c3, EL)
+ fabric_gate(0, e2c3, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e2c3, EL)
+ fabric_gate_r(0, RET, e2c3, EL)

// Auto-generated for /root/.unikraft_akira/apps/base-overhead/cross_server.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example2_empty, EL)
+ fabric_gate(0, example2_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example2_empty, EL)
+ fabric_gate_r(0, RET, example2_empty, EL)

// Auto-generated for /root/.unikraft_akira/apps/base-overhead/cross_server1.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example2_empty, EL)
+ fabric_gate(0, example2_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example2_empty, EL)
+ fabric_gate_r(0, RET, example2_empty, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/example2/example2.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example3_empty, EL)
+ fabric_gate(1, example3_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example3_empty, EL)
+ fabric_gate_r(1, RET, example3_empty, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e3c1, EL)
+ fabric_gate(1, e3c1, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e3c1, EL)
+ fabric_gate_r(1, RET, e3c1, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e3c2, EL)
+ fabric_gate(1, e3c2, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e3c2, EL)
+ fabric_gate_r(1, RET, e3c2, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/example3/example3.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example4_empty, EL)
+ fabric_gate(2, example4_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example4_empty, EL)
+ fabric_gate_r(2, RET, example4_empty, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, e4c1, EL)
+ fabric_gate(2, e4c1, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, e4c1, EL)
+ fabric_gate_r(2, RET, e4c1, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/example4/example4.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, example5_empty, EL)
+ fabric_gate(3, example5_empty, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, example5_empty, EL)
+ fabric_gate_r(3, RET, example5_empty, EL)
