/* Auto-generated by auto_register.py — do not edit */
#include "fabric_init.h"
#include "fabric_register_all.h"
#include "../../../unikraft/lib/fabric-core/backends/include/backends.h"
#include "../../../unikraft/lib/fabric-core/bridge/include/bridge.h"
#include "../../../unikraft/lib/fabric-core/component/include/component.h"
#include "../../../unikraft/lib/fabric-core/controller/include/controller.h"
#include "../../../unikraft/lib/fabric-core/include/fabric_error.h"
#include <flexos/isolation.h>
#include <uk/config.h>
#if CONFIG_LIBFLEXOS_VMEPT
#include <flexos/impl/vmept.h>
#endif
#include <fabric/isolation.h>
#include <stdio.h>
#include <uk/init.h>
#include <uk/page.h>
#include <uk/prio.h>

int fabric_bridge_bind_downstream(struct FabricBridge *bridge, Fabric *fabric);

Fabric *g_comp1_fabric_1 = (void *)0;
Fabric *g_comp1_fabric_2 = (void *)0;
Fabric *g_comp1_fabric_3 = (void *)0;
Fabric *g_comp1_fabric_4 = (void *)0;
Fabric *g_comp1_fabric_5 = (void *)0;


static int fabric_bind_bidi(Fabric *left, Fabric *right)
{
    if (!left || !right || !left->bridge || !right->bridge)
        return FABRIC_ERROR;
    if (fabric_bridge_bind_downstream(left->bridge, right) != FABRIC_SUCCESS)
        return FABRIC_ERROR;
    if (fabric_bridge_bind_downstream(right->bridge, left) != FABRIC_SUCCESS)
        return FABRIC_ERROR;
    return FABRIC_SUCCESS;
}

int fabric_init_all(void)
{
    int rc;

    g_comp1_fabric_1 = fabric_create();
    g_comp1_fabric_2 = fabric_create();
    g_comp1_fabric_3 = fabric_create();
    g_comp1_fabric_4 = fabric_create();
    g_comp1_fabric_5 = fabric_create();
    if (!g_comp1_fabric_1 || !g_comp1_fabric_2 || !g_comp1_fabric_3 || !g_comp1_fabric_4 || !g_comp1_fabric_5)
        return FABRIC_ERROR;

    struct fabric_lib_binding {
        const char *lib_name;
        Fabric *fabric;
        int (*register_fn)(Fabric *);
    };

    struct fabric_lib_binding bindings[] = {
        { "example2", g_comp1_fabric_2, register_example2_functions },
        { "example3", g_comp1_fabric_3, register_example3_functions },
        { "example4", g_comp1_fabric_4, register_example4_functions },
        { "example5", g_comp1_fabric_5, register_example5_functions },
    };
    int binding_count = (int)(sizeof(bindings) / sizeof(bindings[0]));
    for (int i = 0; i < binding_count; i++) {
        rc = bindings[i].register_fn(bindings[i].fabric);
        if (rc != FABRIC_SUCCESS)
            return rc;
    }

    rc = fabric_bind_bidi(g_comp1_fabric_1, g_comp1_fabric_2);
    if (rc != FABRIC_SUCCESS)
        return rc;
    rc = fabric_bind_bidi(g_comp1_fabric_2, g_comp1_fabric_3);
    if (rc != FABRIC_SUCCESS)
        return rc;
    rc = fabric_bind_bidi(g_comp1_fabric_3, g_comp1_fabric_4);
    if (rc != FABRIC_SUCCESS)
        return rc;
    rc = fabric_bind_bidi(g_comp1_fabric_4, g_comp1_fabric_5);
    if (rc != FABRIC_SUCCESS)
        return rc;

    /* --- 隔离后端初始化（MPK；消融测 enter/leave 的 wrpkru 路径） --- */
    {
        MPKConfig iso_cfg;
        iso_cfg.fabric_id = g_comp1_fabric_1->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_1->bridge, FABRIC_ISO_MPK, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_2->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_2->bridge, FABRIC_ISO_MPK, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_3->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_3->bridge, FABRIC_ISO_MPK, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_4->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_4->bridge, FABRIC_ISO_MPK, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_5->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_5->bridge, FABRIC_ISO_MPK, &iso_cfg);
    }

    /*
     * Skip MPK page tagging for ablation when fabric section symbols are
     * stale / SKIP_FABRIC_SECTIONS (wrong addresses → PF_PK). Isolation
     * enter/leave still exercise rdpkru/wrpkru for cycle accounting.
     */
    printf("[AKIRA-MPK] skip page tagging (ablation / shared sections)\n");

    return FABRIC_SUCCESS;
}

static int __fabric_lib_init(void)
{
    return fabric_init_all();
}
uk_lib_initcall_prio(__fabric_lib_init, UK_PRIO_EARLIEST);
