/* Auto-generated by auto_register.py — chain symbols shortened for FNV bench */
#include "fabric_register_all.h"
#include <uk/print.h>

extern const char __fsym_example2_empty[] __asm__("example2_empty") __attribute__((weak));
extern const char __fsym_e2_call_e3_direct[] __asm__("e2_call_e3_direct") __attribute__((weak));
extern const char __fsym_e2_call_e3_msg[] __asm__("e2_call_e3_msg") __attribute__((weak));
extern const char __fsym_e2c1[] __asm__("e2c1") __attribute__((weak));
extern const char __fsym_e2c2[] __asm__("e2c2") __attribute__((weak));
extern const char __fsym_e2c3[] __asm__("e2c3") __attribute__((weak));
extern const char __fsym_example3_empty[] __asm__("example3_empty") __attribute__((weak));
extern const char __fsym_e3c1[] __asm__("e3c1") __attribute__((weak));
extern const char __fsym_e3c2[] __asm__("e3c2") __attribute__((weak));
extern const char __fsym_example4_empty[] __asm__("example4_empty") __attribute__((weak));
extern const char __fsym_e4c1[] __asm__("e4c1") __attribute__((weak));
extern const char __fsym_example5_empty[] __asm__("example5_empty") __attribute__((weak));

int register_example2_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_example2_empty == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: example2_empty (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "example2_empty", (func_t)(void *)__fsym_example2_empty);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e2_call_e3_direct == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e2_call_e3_direct (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e2_call_e3_direct",
                                     (func_t)(void *)__fsym_e2_call_e3_direct);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e2_call_e3_msg == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e2_call_e3_msg (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e2_call_e3_msg",
                                     (func_t)(void *)__fsym_e2_call_e3_msg);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e2c1 == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e2c1 (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e2c1", (func_t)(void *)__fsym_e2c1);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e2c2 == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e2c2 (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e2c2", (func_t)(void *)__fsym_e2c2);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e2c3 == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e2c3 (example2)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e2c3", (func_t)(void *)__fsym_e2c3);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] example2: %d registered, %d missing, 6 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_example3_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_example3_empty == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: example3_empty (example3)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "example3_empty", (func_t)(void *)__fsym_example3_empty);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e3c1 == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e3c1 (example3)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e3c1", (func_t)(void *)__fsym_e3c1);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e3c2 == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e3c2 (example3)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e3c2", (func_t)(void *)__fsym_e3c2);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] example3: %d registered, %d missing, 3 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_example4_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_example4_empty == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: example4_empty (example4)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "example4_empty", (func_t)(void *)__fsym_example4_empty);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_e4c1 == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: e4c1 (example4)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "e4c1", (func_t)(void *)__fsym_e4c1);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] example4: %d registered, %d missing, 2 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_example5_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_example5_empty == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: example5_empty (example5)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "example5_empty", (func_t)(void *)__fsym_example5_empty);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] example5: %d registered, %d missing, 1 total\n", registered, missing);
    return FABRIC_SUCCESS;
}
