// Auto-generated by auto_register.py — do not edit

// Auto-generated for /root/.unikraft_akira/libs/pthread-embedded/attributes.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_get_prio, EL)
+ fabric_gate(0, uk_thread_get_prio, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_get_prio, EL)
+ fabric_gate_r(0, RET, uk_thread_get_prio, EL)

// Auto-generated for /root/.unikraft_akira/libs/pthread-embedded/pte_osal.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_exit, EL)
+ fabric_gate(0, uk_sched_thread_exit, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_exit, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_exit, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_sleep, EL)
+ fabric_gate(0, uk_sched_thread_sleep, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_sleep, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_sleep, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_get_prio, EL)
+ fabric_gate(0, uk_thread_get_prio, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_get_prio, EL)
+ fabric_gate_r(0, RET, uk_thread_get_prio, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_inherit_signal_mask, EL)
+ fabric_gate(0, uk_thread_inherit_signal_mask, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_inherit_signal_mask, EL)
+ fabric_gate_r(0, RET, uk_thread_inherit_signal_mask, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_set_prio, EL)
+ fabric_gate(0, uk_thread_set_prio, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_set_prio, EL)
+ fabric_gate_r(0, RET, uk_thread_set_prio, EL)

@noreturn_5@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wait, EL)
+ fabric_gate(0, uk_thread_wait, EL)

@return_5@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wait, EL)
+ fabric_gate_r(0, RET, uk_thread_wait, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uk9p/9pdev.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uk9p/9preq.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uklock/include/uk/mutex.h

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uklock/include/uk/semaphore.h

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uknetdev/netdev.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_create, EL)
+ fabric_gate(0, uk_sched_thread_create, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_create, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_create, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wait, EL)
+ fabric_gate(0, uk_thread_wait, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wait, EL)
+ fabric_gate_r(0, RET, uk_thread_wait, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uksched/sched.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, flexos_intelpku_mem_set_key, EL)
+ fabric_gate(1, flexos_intelpku_mem_set_key, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, flexos_intelpku_mem_set_key, EL)
+ fabric_gate_r(1, RET, flexos_intelpku_mem_set_key, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uktime/time.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_sleep, EL)
+ fabric_gate(0, uk_sched_thread_sleep, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_sleep, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_sleep, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/vfscore/pipe.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Disable direct uk_lib_initcall for fabric-isolated library
@disable_liblwip_init@
@@
-uk_lib_initcall(liblwip_init);
+/* fabric-isolated: liblwip_init invoked via fabric gate */
