/* Auto-generated by auto_register.py — do not edit */
#include "fabric_register_all.h"
#include <uk/print.h>

extern const char __fsym_flexos_intelpku_mem_set_key[] __asm__("flexos_intelpku_mem_set_key") __attribute__((weak));
extern const char __fsym_uk_sched_thread_create[] __asm__("uk_sched_thread_create") __attribute__((weak));
extern const char __fsym_uk_sched_thread_exit[] __asm__("uk_sched_thread_exit") __attribute__((weak));
extern const char __fsym_uk_sched_thread_sleep[] __asm__("uk_sched_thread_sleep") __attribute__((weak));
extern const char __fsym_uk_thread_get_prio[] __asm__("uk_thread_get_prio") __attribute__((weak));
extern const char __fsym_uk_thread_inherit_signal_mask[] __asm__("uk_thread_inherit_signal_mask") __attribute__((weak));
extern const char __fsym_uk_thread_set_prio[] __asm__("uk_thread_set_prio") __attribute__((weak));
extern const char __fsym_uk_thread_wait[] __asm__("uk_thread_wait") __attribute__((weak));
extern const char __fsym_uk_thread_wake[] __asm__("uk_thread_wake") __attribute__((weak));
extern const char __fsym__liblwip_init[] __asm__("_liblwip_init") __attribute__((weak));

int register_flexos_core_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_flexos_intelpku_mem_set_key == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: flexos_intelpku_mem_set_key (flexos_core)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "flexos_intelpku_mem_set_key", (func_t)(void *)__fsym_flexos_intelpku_mem_set_key);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] flexos_core: %d registered, %d missing, 1 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_uksched_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_uk_sched_thread_create == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_sched_thread_create (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_sched_thread_create", (func_t)(void *)__fsym_uk_sched_thread_create);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_sched_thread_exit == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_sched_thread_exit (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_sched_thread_exit", (func_t)(void *)__fsym_uk_sched_thread_exit);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_sched_thread_sleep == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_sched_thread_sleep (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_sched_thread_sleep", (func_t)(void *)__fsym_uk_sched_thread_sleep);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_get_prio == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_get_prio (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_get_prio", (func_t)(void *)__fsym_uk_thread_get_prio);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_inherit_signal_mask == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_inherit_signal_mask (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_inherit_signal_mask", (func_t)(void *)__fsym_uk_thread_inherit_signal_mask);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_set_prio == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_set_prio (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_set_prio", (func_t)(void *)__fsym_uk_thread_set_prio);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_wait == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_wait (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_wait", (func_t)(void *)__fsym_uk_thread_wait);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_wake == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_wake (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_wake", (func_t)(void *)__fsym_uk_thread_wake);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] uksched: %d registered, %d missing, 8 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_lwip_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym__liblwip_init == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: _liblwip_init (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "_liblwip_init", (func_t)(void *)__fsym__liblwip_init);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] lwip: %d registered, %d missing, 1 total\n", registered, missing);
    return FABRIC_SUCCESS;
}
