#!/usr/bin/env python3
"""Fabric code generator — single entry point for all generated artifacts.

Reads ``fabric.yaml`` + ``kraft.yaml`` via ``parse_config.analyze()``, then
generates:

- ``fabric_register_all.h`` / ``register_all.c`` — per-library registration
- ``fabric_init.h`` / ``fabric_init.c`` — fabric creation, isolation init,
  bridge wiring, function registration
- Coccinelle ``.cocci`` rules + ``apply_fabric_rules.sh`` — rewrite
  ``flexos_nop_gate`` → ``fabric_gate`` in source files
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

# Add parse_config directory to path so we can import its functions
_parse_config_dir = str(Path(__file__).resolve().parent.parent / "parse_config")
if _parse_config_dir not in sys.path:
    sys.path.insert(0, _parse_config_dir)

from parse_config import (
    AnalysisResult,
    CallSite,
    ISO_MAP,
    analyze,
    c_safe,
    fabric_core_rel,
    normalise_lib_name,
)

# Libraries with uk_lib_initcall entry points that must not run directly
# when placed in a non-default fabric (MPK would fault on direct call).
ISOLATED_LIB_INITCALLS: dict[str, dict[str, Any]] = {
    "lwip": {
        "init_fn": "liblwip_init",
        "gate_sym": "_liblwip_init",
        "init_source": ("lwip", "init.c"),
    },
}


def find_isolated_lib_initcalls(
    fabric_libs: dict[str, list[str]],
    default_fabrics: dict[str, str] | None,
    ext_lib_root: Path | None,
    lib_fabric: dict[str, int] | None = None,
    fabric_names: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Return isolated libs whose initcall must be routed through fabric_gate."""
    default_names = set(default_fabrics.values()) if default_fabrics else set()
    fabric_index = {name: idx for idx, name in enumerate(fabric_names or [])}
    found: list[dict[str, Any]] = []
    if ext_lib_root is None:
        return found

    for fname, libs in fabric_libs.items():
        if fname in default_names:
            continue
        for lib in libs:
            meta = ISOLATED_LIB_INITCALLS.get(lib)
            if meta is None:
                continue
            rel_lib, rel_file = meta["init_source"]
            source = ext_lib_root / rel_lib / rel_file
            if not source.exists():
                continue
            fabric_idx = None
            if lib_fabric and lib in lib_fabric:
                fabric_idx = lib_fabric[lib]
            elif fname in fabric_index:
                fabric_idx = fabric_index[fname]
            if fabric_idx is None:
                continue
            found.append({
                "lib": lib,
                "init_fn": meta["init_fn"],
                "gate_sym": meta["gate_sym"],
                "fabric_idx": fabric_idx,
                "source": source.resolve(),
                "stub": f"__fabric_isolated_{normalise_lib_name(lib)}_init",
            })
    return found


# ===================================================================
#  代码生成 — 注册辅助
# ===================================================================

def render_register_all_h(reg_plan: dict[str, list[str]], fc_rel: str) -> str:
    lines = [
        "/* Auto-generated by auto_register.py — do not edit */",
        "#ifndef _FABRIC_REGISTER_ALL_H_",
        "#define _FABRIC_REGISTER_ALL_H_",
        "",
        f'#include "{fc_rel}/include/fabric_error.h"',
        f'#include "{fc_rel}/fabric/include/fabric.h"',
        "",
        "typedef struct Fabric Fabric;",
        "typedef void (*func_t)(void);",
        "int fabric_register_function(Fabric *fabric, const char *func_name, func_t func_ptr);",
        "",
    ]
    for lib in reg_plan:
        lines.append(f"int register_{lib}_functions(Fabric *fabric);")
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_register_all_c(reg_plan: dict[str, list[str]]) -> str:
    lines = [
        "/* Auto-generated by auto_register.py — do not edit */",
        '#include "fabric_register_all.h"',
        '#include <uk/print.h>',
        "",
    ]
    # Weak extern declarations
    for funcs in reg_plan.values():
        for func in funcs:
            lines.append(f'extern const char __fsym_{func}[] __asm__("{func}") __attribute__((weak));')
    lines.append("")

    for lib, funcs in reg_plan.items():
        lines.append(f"int register_{lib}_functions(Fabric *fabric)")
        lines.append("{")
        lines.append("    int rc;")
        lines.append("    int registered = 0;")
        lines.append("    int missing = 0;")
        for func in funcs:
            lines.append(f"    if (__fsym_{func} == (const char *)0) {{")
            lines.append(f'        uk_pr_info("[fabric-register] skip unresolved: {func} ({lib})\\n");')
            lines.append("        missing++;")
            lines.append("    } else {")
            lines.append(f'        rc = fabric_register_function(fabric, "{func}", (func_t)(void *)__fsym_{func});')
            lines.append("        if (rc != FABRIC_SUCCESS)")
            lines.append("            return rc;")
            lines.append("        registered++;")
            lines.append("    }")
        lines.append(
            f'    uk_pr_info("[fabric-register] {lib}: %d registered, %d missing, {len(funcs)} total\\n",'
            " registered, missing);"
        )
        lines.append("    return FABRIC_SUCCESS;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


# ===================================================================
#  代码生成 — fabric 初始化
# ===================================================================

def render_fabric_init_h(fabric_names: list[str], fc_rel: str) -> str:
    lines = [
        "/* Auto-generated by auto_register.py — do not edit */",
        "#ifndef _FABRIC_INIT_H_",
        "#define _FABRIC_INIT_H_",
        "",
        f'#include "{fc_rel}/fabric/include/fabric.h"',
        "",
    ]
    for name in fabric_names:
        lines.append(f"extern Fabric *g_{c_safe(name)};")
    lines.extend(["", "int fabric_init_all(void);", "", "#endif", ""])
    return "\n".join(lines)


def render_fabric_init_c(
    fabric_names: list[str],
    fabric_libs: dict[str, list[str]],
    edges: list[tuple[str, str]],
    reg_plan: dict[str, list[str]],
    lib_fabric: dict[str, int],
    default_fabric: int,
    isolation_backend: str = "ept",
    fc_rel: str = "../fabric-core",
    default_fabrics: dict[str, str] | None = None,
    skip_page_tagging: bool = False,
    isolated_initcalls: list[dict[str, Any]] | None = None,
) -> str:
    lines = [
        "/* Auto-generated by auto_register.py — do not edit */",
        '#include "fabric_init.h"',
        '#include "fabric_register_all.h"',
        f'#include "{fc_rel}/backends/include/backends.h"',
        f'#include "{fc_rel}/bridge/include/bridge.h"',
        f'#include "{fc_rel}/component/include/component.h"',
        f'#include "{fc_rel}/controller/include/controller.h"',
        f'#include "{fc_rel}/include/fabric_error.h"',
        '#include <flexos/isolation.h>',
    ]
    if isolation_backend == "mpk":
        lines.append('#include <flexos/impl/intelpku.h>')
    elif isolation_backend == "ept":
        lines.append('#include <uk/config.h>')
        lines.append('#if CONFIG_LIBFLEXOS_VMEPT')
        lines.append('#include <flexos/impl/vmept.h>')
        lines.append('#endif')
    lines.extend([
        '#include <fabric/isolation.h>',
        '#include <stdio.h>',
        '#include <uk/init.h>',
        '#include <uk/page.h>',
        '#include <uk/prio.h>',
        "",
        "int fabric_bridge_bind_downstream(struct FabricBridge *bridge, Fabric *fabric);",
        "",
    ])

    # 全局 fabric 指针
    for name in fabric_names:
        lines.append(f"Fabric *g_{c_safe(name)} = (void *)0;")
    lines.extend(["", ""])

    # 双向桥接辅助函数
    lines.extend([
        "static int fabric_bind_bidi(Fabric *left, Fabric *right)",
        "{",
        "    if (!left || !right || !left->bridge || !right->bridge)",
        "        return FABRIC_ERROR;",
        "    if (fabric_bridge_bind_downstream(left->bridge, right) != FABRIC_SUCCESS)",
        "        return FABRIC_ERROR;",
        "    if (fabric_bridge_bind_downstream(right->bridge, left) != FABRIC_SUCCESS)",
        "        return FABRIC_ERROR;",
        "    return FABRIC_SUCCESS;",
        "}",
        "",
    ])

    # fabric_init_all()
    lines.extend([
        "int fabric_init_all(void)",
        "{",
        "    int rc;",
        "",
    ])

    # 创建 fabric
    for name in fabric_names:
        cname = c_safe(name)
        lines.append(f"    g_{cname} = fabric_create();")
    guard = " || ".join(f"!g_{c_safe(name)}" for name in fabric_names)
    lines.append(f"    if ({guard})")
    lines.append("        return FABRIC_ERROR;")
    lines.append("")

    # 注册函数
    lines.append("    struct fabric_lib_binding {")
    lines.append("        const char *lib_name;")
    lines.append("        Fabric *fabric;")
    lines.append("        int (*register_fn)(Fabric *);")
    lines.append("    };")
    lines.append("")
    lines.append("    struct fabric_lib_binding bindings[] = {")
    seen_bindings: set[tuple[str, str]] = set()
    for lib in sorted(reg_plan.keys()):
        fabric_idx = lib_fabric.get(lib, default_fabric)
        if fabric_idx < 0 or fabric_idx >= len(fabric_names):
            continue
        fabric_name = fabric_names[fabric_idx]
        key = (lib, fabric_name)
        if key in seen_bindings:
            continue
        seen_bindings.add(key)
        cname = c_safe(fabric_name)
        lines.append(f'        {{ "{lib}", g_{cname}, register_{lib}_functions }},')
    lines.append("    };")
    lines.append("    int binding_count = (int)(sizeof(bindings) / sizeof(bindings[0]));")
    lines.append("    for (int i = 0; i < binding_count; i++) {")
    lines.append("        rc = bindings[i].register_fn(bindings[i].fabric);")
    lines.append("        if (rc != FABRIC_SUCCESS)")
    lines.append("            return rc;")
    lines.append("    }")
    lines.append("")

    # 连接桥接边
    for left, right in edges:
        lines.append(f"    rc = fabric_bind_bidi(g_{c_safe(left)}, g_{c_safe(right)});")
        lines.append("    if (rc != FABRIC_SUCCESS)")
        lines.append("        return rc;")
    lines.append("")

    # 隔离后端初始化（在桥接绑定之后，确保 downstream 拓扑已就绪）
    iso_enum, iso_cfg_type = ISO_MAP.get(isolation_backend, ("", ""))
    if iso_enum:
        lines.append("    /* --- 隔离后端初始化 --- */")
        lines.append("    {")
        lines.append(f"        {iso_cfg_type} iso_cfg;")
        for name in fabric_names:
            cname = c_safe(name)
            lines.append(f"        iso_cfg.fabric_id = g_{cname}->fabric_id;")
            lines.append(f"        fabric_bridge_set_isolation(g_{cname}->bridge, {iso_enum}, &iso_cfg);")
        lines.append("    }")
        lines.append("")
    else:
        lines.append(f"    /* [warning] 未知的隔离后端: {isolation_backend}，跳过隔离初始化 */")
        lines.append("")

    # MPK 内存页面标记（非默认 fabric 的 section 打上 fabric key）
    default_names = set(default_fabrics.values()) if default_fabrics else set()
    iso_fabrics = [n for n in fabric_names if n not in default_names]
    if iso_fabrics and isolation_backend == "mpk" and not skip_page_tagging:
        lines.append("    /* --- MPK 内存页面标记 --- */")
        lines.append("    {")
        lines.append("        extern int flexos_intelpku_mem_set_key(void *, uint64_t, uint8_t);")
        for name in iso_fabrics:
            cname = c_safe(name)
            lines.append(f"        extern char _fabric_{cname}_data_start[], _fabric_{cname}_data_end[];")
            lines.append(f"        extern char _fabric_{cname}_bss_start[], _fabric_{cname}_bss_end[];")
            lines.append(f"        extern char _fabric_{cname}_text_start[], _fabric_{cname}_text_end[];")
        lines.append("")
        for name in iso_fabrics:
            cname = c_safe(name)
            lines.append(f"        /* tag {name} sections with fabric key */")
            lines.append(f"        do {{")
            # Do not printf here: after uksched pages get a non-zero key,
            # stdio locking may call uk_sched_get_default() and PF_PK on .bss.
            lines.append(f"            MPKBridgeState *_st = g_{cname}->bridge->iso_state ?")
            lines.append(f"                (MPKBridgeState *)g_{cname}->bridge->iso_state : (void *)0;")
            lines.append(f"            uint32_t _key = _st ? _st->my_key : 0;")
            lines.append(f"            if (_key > 0) {{")
            lines.append(f"                uintptr_t _s, _e, _np;")
            lines.append(f"                _s = (uintptr_t)_fabric_{cname}_data_start & ~(uintptr_t)0xFFF;")
            lines.append(f"                _e = ((uintptr_t)_fabric_{cname}_data_end + 0xFFF) & ~(uintptr_t)0xFFF;")
            lines.append(f"                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;")
            lines.append(f"                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);")
            lines.append(f"                _s = (uintptr_t)_fabric_{cname}_bss_start & ~(uintptr_t)0xFFF;")
            lines.append(f"                _e = ((uintptr_t)_fabric_{cname}_bss_end + 0xFFF) & ~(uintptr_t)0xFFF;")
            lines.append(f"                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;")
            lines.append(f"                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);")
            lines.append(f"                _s = (uintptr_t)_fabric_{cname}_text_start & ~(uintptr_t)0xFFF;")
            lines.append(f"                _e = ((uintptr_t)_fabric_{cname}_text_end + 0xFFF) & ~(uintptr_t)0xFFF;")
            lines.append(f"                _np = (_e > _s) ? (_e - _s) / __PAGE_SIZE : 0;")
            lines.append(f"                if (_np) flexos_intelpku_mem_set_key((void *)_s, _np, _key);")
            lines.append(f"            }}")
            lines.append(f"        }} while (0);")
        lines.append("    }")
        lines.append("")

    lines.extend([
        "    return FABRIC_SUCCESS;",
        "}",
        "",
    ])

    isolated_initcalls = isolated_initcalls or []
    for item in isolated_initcalls:
        lines.append(f"extern int {item['gate_sym']}(void);")
    if isolated_initcalls:
        lines.append("")
    for item in isolated_initcalls:
        lines.extend([
            f"/* Route {item['init_fn']} through fabric gate (lib in non-default fabric). */",
            f"static int {item['stub']}(void)",
            "{",
            "    int rc = 0;",
            "#if CONFIG_LIBFLEXOS_VMEPT",
            "    /* Library VMs must reach master_rpc_loop before any cross-comp",
            "     * gate. Only the app compartment drives isolated lib inits",
            "     * (after boot.c has created peer RPC threads). */",
            "    if (flexos_vmept_comp_id != FLEXOS_VMEPT_APPCOMP)",
            "        return 0;",
            "#endif",
            f"    fabric_gate_r({default_fabric}, rc, {item['gate_sym']});",
            "    return rc;",
            "}",
            f"uk_lib_initcall_prio({item['stub']}, UK_PRIO_LATEST);",
            "",
        ])

    lines.extend([
        "static int __fabric_lib_init(void)",
        "{",
        "    return fabric_init_all();",
        "}",
        "uk_lib_initcall_prio(__fabric_lib_init, UK_PRIO_EARLIEST);",
        "",
    ])
    return "\n".join(lines)


# ===================================================================
#  代码生成 — Coccinelle 重写规则
# ===================================================================

def build_rewrite_plan(
    cross_calls: list[CallSite],
    lib_fabric: dict[str, int],
    default_fabric: int,
) -> dict[Path, dict[str, Any]]:
    """Map source file → {src_fabric: int, funcs: set[str]}."""
    by_file: dict[Path, dict[str, Any]] = {}
    for call in cross_calls:
        if not call.registerable:
            continue
        caller_fabric = lib_fabric.get(call.caller_lib, default_fabric)
        callee_fabric = lib_fabric.get(call.callee_lib, default_fabric)
        if caller_fabric == callee_fabric:
            continue
        data = by_file.setdefault(call.path, {"src_fabric": caller_fabric, "funcs": set()})
        data["funcs"].add(call.func)
    return by_file


def render_cocci_rules_for_file(src_fabric: int, funcs: list[str], label: str) -> str:
    """Generate Coccinelle rules for one source file."""
    lines = [f"// Auto-generated for {label}", ""]
    for idx, func in enumerate(funcs):
        lines.extend([
            f"@noreturn_{idx}@",
            "expression list EL;",
            "expression COMP_FROM, COMP_TO;",
            "@@",
            f"- flexos_nop_gate(COMP_FROM, COMP_TO, {func}, EL)",
            f"+ fabric_gate({src_fabric}, {func}, EL)",
            "",
            f"@return_{idx}@",
            "expression list EL;",
            "expression COMP_FROM, COMP_TO, RET;",
            "@@",
            f"- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, {func}, EL)",
            f"+ fabric_gate_r({src_fabric}, RET, {func}, EL)",
            "",
        ])
    return "\n".join(lines) + "\n"


def render_isolated_lwip_sync_init_cocci() -> str:
    # Match both nop and vmept gates (VMEPT builds rewrite nop→vmept first).
    return """// Force synchronous lwip_init when lwip runs in an isolated fabric
@lwip_sync_init_for_isolation@
@@
-	tcpip_init(_lwip_init_done, NULL);
-
-	/* Wait until stack is booted */
-	flexos_vmept_gate(0, 0, uk_semaphore_down, &_lwip_init_sem);
+	/* fabric-isolated: sync init (avoid cross-VM sem deadlock on VMEPT) */
+	lwip_init();

@lwip_sync_init_for_isolation_nop@
@@
-	tcpip_init(_lwip_init_done, NULL);
-
-	/* Wait until stack is booted */
-	flexos_nop_gate(0, 0, uk_semaphore_down, &_lwip_init_sem);
+	/* fabric-isolated: sync init */
+	lwip_init();
"""


def render_disable_initcall_cocci(init_fn: str) -> str:
  return f"""// Disable direct uk_lib_initcall for fabric-isolated library
@disable_{init_fn}@
@@
-uk_lib_initcall({init_fn});
+/* fabric-isolated: {init_fn} invoked via fabric gate */
"""


def write_rewrite_artifacts(
    out_dir: Path,
    rewrite_plan: dict[Path, dict[str, Any]],
    isolated_initcalls: list[dict[str, Any]] | None = None,
) -> None:
    """Write Coccinelle rules and apply script to out_dir."""
    cocci_dir = out_dir / "cocci"
    cocci_dir.mkdir(parents=True, exist_ok=True)

    # Remove stale rules
    for stale in cocci_dir.glob("rule_*.cocci"):
        stale.unlink()

    merged_lines = ["// Auto-generated by auto_register.py — do not edit", ""]

    script_lines = [
        "#!/bin/sh",
        "set -eu",
        "",
        "ensure_include() {",
        "    file=$1",
        "    if grep -q 'fabric/isolation.h' \"$file\" 2>/dev/null; then",
        "        return 0",
        "    fi",
        "    python3 - \"$file\" <<'PY'",
        "from pathlib import Path",
        "import sys",
        "path = Path(sys.argv[1])",
        "text = path.read_text(encoding='utf-8')",
        "needle = '#include <flexos/isolation.h>\\n'",
        "insert = '#include <flexos/isolation.h>\\n#include <fabric/isolation.h>\\n'",
        "if 'fabric/isolation.h' in text:",
        "    raise SystemExit(0)",
        "if needle in text:",
        "    text = text.replace(needle, insert, 1)",
        "else:",
        "    text = '#include <fabric/isolation.h>\\n' + text",
        "path.write_text(text, encoding='utf-8')",
        "PY",
        "}",
        "",
    ]

    if not rewrite_plan and not isolated_initcalls:
        script_lines.append("echo '[fabric] no cross-fabric rewrites required'")

    rule_idx = 0
    for path, data in sorted(rewrite_plan.items(), key=lambda item: str(item[0])):
        funcs = sorted(data["funcs"])
        cocci_path = cocci_dir / f"rule_{rule_idx}.cocci"
        contents = render_cocci_rules_for_file(data["src_fabric"], funcs, str(path))
        cocci_path.write_text(contents, encoding="utf-8")
        merged_lines.append(contents.rstrip())
        merged_lines.append("")
        script_lines.append(f"spatch --sp-file '{cocci_path}' '{path}' --in-place")
        script_lines.append(f"ensure_include '{path}'")
        rule_idx += 1

    for item in isolated_initcalls or []:
        cocci_path = cocci_dir / f"rule_{rule_idx}.cocci"
        contents = render_disable_initcall_cocci(item["init_fn"])
        cocci_path.write_text(contents, encoding="utf-8")
        merged_lines.append(contents.rstrip())
        merged_lines.append("")
        script_lines.append(
            f"spatch --sp-file '{cocci_path}' '{item['source']}' --in-place || true"
        )
        rule_idx += 1

    # Intentionally skip sync-init cocci: tcpip_init is required for Redis
    # Socket API (NO_SYS=0). It works when MPK section tagging is skipped.
    lwip_items = []
    if False and lwip_items:
        pass

    (out_dir / "fabric_gates_rules.cocci").write_text(
        "\n".join(merged_lines).rstrip() + "\n", encoding="utf-8"
    )
    apply_script = out_dir / "apply_fabric_rules.sh"
    apply_script.write_text("\n".join(script_lines) + "\n", encoding="utf-8")
    apply_script.chmod(0o755)


# ===================================================================
#  主入口 — 统一生成所有产物
# ===================================================================

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Fabric code generator — produces registration, init, and Coccinelle artifacts."
    )
    parser.add_argument("--app-dir", type=Path, required=True,
                        help="Application directory containing fabric.yaml and kraft.yaml")
    parser.add_argument("--out-dir", type=Path, required=True,
                        help="Output directory for generated files")
    parser.add_argument("--lib-root", type=Path, required=True,
                        help="Root directory of unikraft libs (e.g. unikraft/lib)")
    parser.add_argument("--ext-lib-root", type=Path, default=None,
                        help="Root directory of external libs (e.g. libs/)")
    parser.add_argument("--skip-page-tagging", action="store_true",
                        help="Skip MPK page tagging code generation (for pre-injection build)")
    args = parser.parse_args()

    # ------------------------------------------------------------------
    # 1. 统一分析
    # ------------------------------------------------------------------
    try:
        result = analyze(args.app_dir, args.lib_root, args.ext_lib_root)
    except FileNotFoundError as e:
        print(f"[error] {e}", file=sys.stderr)
        return 1

    print(f"[info] app library name : {result.app_lib_name}")
    print(f"[info] app runtime lib  : {result.app_runtime_lib}")
    print(f"[info] default compartment: {result.default_compartment}")
    print(f"[info] isolation backend: {result.isolation_backend}")
    print(f"[info] fabrics ({len(result.fabric_names)}):")
    for i, name in enumerate(result.fabric_names):
        libs = result.fabric_libs.get(name, [])
        print(f"  [{i}] {name}: {', '.join(libs) or '(empty)'}")
    print(f"[info] bridge edges ({len(result.edges)}):")
    for left, right in result.edges:
        print(f"  {left} <-> {right}")
    print(f"[info] function index: {len(result.function_index)} entries")
    print(f"[info] export index  : {len(result.export_index)} entries")
    print(f"[info] nop_gate call sites  : {len(result.call_sites)}")
    print(f"[info] cross-fabric calls   : {len(result.cross_calls)}")

    # ------------------------------------------------------------------
    # 2. 计算相对路径
    # ------------------------------------------------------------------
    out_dir = args.out_dir.resolve()
    fc_rel = fabric_core_rel(out_dir, args.lib_root.resolve())
    print(f"[info] fabric-core relative path: {fc_rel}")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 3. 生成注册文件
    # ------------------------------------------------------------------
    reg_plan = dict(result.reg_plan)
    isolated_initcalls = find_isolated_lib_initcalls(
        result.fabric_libs, result.default_fabrics, args.ext_lib_root,
        result.lib_fabric, result.fabric_names,
    )
    for item in isolated_initcalls:
        print(
            f"[info] isolated initcall: {item['init_fn']} -> "
            f"fabric_gate({item['fabric_idx']}, {item['gate_sym']})"
        )

    for fname, libs in result.fabric_libs.items():
        if fname in set(result.default_fabrics.values()):
            continue
        if "lwip" in libs:
            funcs = set(reg_plan.get("lwip", []))
            funcs.add("_liblwip_init")
            reg_plan["lwip"] = sorted(funcs)
            break

    (args.out_dir / "fabric_register_all.h").write_text(
        render_register_all_h(reg_plan, fc_rel), encoding="utf-8"
    )
    (args.out_dir / "register_all.c").write_text(
        render_register_all_c(reg_plan), encoding="utf-8"
    )

    # ------------------------------------------------------------------
    # 4. 生成初始化文件
    # ------------------------------------------------------------------
    (args.out_dir / "fabric_init.h").write_text(
        render_fabric_init_h(result.fabric_names, fc_rel), encoding="utf-8"
    )
    (args.out_dir / "fabric_init.c").write_text(
        render_fabric_init_c(
            result.fabric_names, result.fabric_libs, result.edges,
            reg_plan, result.lib_fabric, result.default_fabric,
            result.isolation_backend, fc_rel,
            default_fabrics=result.default_fabrics,
            skip_page_tagging=args.skip_page_tagging,
            isolated_initcalls=isolated_initcalls,
        ),
        encoding="utf-8",
    )

    # ------------------------------------------------------------------
    # 5. 生成 per-library linker script（用于 partial link 阶段重命名 section）
    # ------------------------------------------------------------------
    default_fabric_names = set(result.default_fabrics.values())
    lib_ld_count = 0
    for fname, libs in result.fabric_libs.items():
        if fname in default_fabric_names or not libs:
            continue
        safe = c_safe(fname)
        for lib in libs:
            # per-library partial link 阶段只有一个库的 .o 文件，
            # 用 * 通配符匹配即可（不会有其他库的对象混入）
            ld_content = "\n".join([
                "SECTIONS {",
                f"    .data_{safe} : {{",
                f"        *(.data .data.* .rodata .rodata.* .sdata .sdata.*)",
                f"    }}",
                f"    .bss_{safe} : {{",
                f"        *(.bss .bss.* .sbss .sbss.* COMMON)",
                f"    }}",
                f"    .text_{safe} : {{",
                f"        *(.text .text.*)",
                f"    }}",
                "}",
                "",
            ])
            ld_path = args.out_dir / f"lib_{lib}_fabric.ld"
            ld_path.write_text(ld_content, encoding="utf-8")
            lib_ld_count += 1
    print(f"[info] per-library linker scripts: {lib_ld_count}")

    # ------------------------------------------------------------------
    # 6. 生成 Coccinelle 重写规则
    # ------------------------------------------------------------------
    rewrite_plan = build_rewrite_plan(
        result.cross_calls, result.lib_fabric, result.default_fabric
    )
    write_rewrite_artifacts(args.out_dir, rewrite_plan, isolated_initcalls)

    # ------------------------------------------------------------------
    # 输出摘要
    # ------------------------------------------------------------------
    total_funcs = sum(len(v) for v in reg_plan.values())
    print(f"[info] registered functions: {total_funcs}")
    for lib, funcs in sorted(reg_plan.items()):
        print(f"  [register] {lib}: {', '.join(funcs)}")
    skipped = sorted({c.func for c in result.cross_calls if not c.registerable})
    for func in skipped:
        print(f"  [direct] {func}")
    print(f"[info] rewrite plan: {len(rewrite_plan)} file(s)")
    for path, data in sorted(rewrite_plan.items(), key=lambda x: str(x[0])):
        print(f"  [rewrite] {path} ({len(data['funcs'])} funcs)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
