# (1) 1 domain, MPK, no software hardening
isolation:
  backend: ept

comp1:
  fabrics:
    fabric-1:
      default: true
      libs:
        - fabric-core
        - flexos-core
        - redis
        - newlib
        - tlsf
        - pthread-embedded
        - lwip
