/* Auto-generated by auto_register.py — do not edit */
#include "fabric_init.h"
#include "fabric_register_all.h"
#include "../../../unikraft/lib/fabric-core/backends/include/backends.h"
#include "../../../unikraft/lib/fabric-core/bridge/include/bridge.h"
#include "../../../unikraft/lib/fabric-core/component/include/component.h"
#include "../../../unikraft/lib/fabric-core/controller/include/controller.h"
#include "../../../unikraft/lib/fabric-core/include/fabric_error.h"
#include <flexos/isolation.h>
#include <uk/config.h>
#if CONFIG_LIBFLEXOS_VMEPT
#include <flexos/impl/vmept.h>
#endif
#include <fabric/isolation.h>
#include <stdio.h>
#include <uk/init.h>
#include <uk/page.h>
#include <uk/prio.h>

int fabric_bridge_bind_downstream(struct FabricBridge *bridge, Fabric *fabric);

Fabric *g_comp1_fabric_1 = (void *)0;
Fabric *g_comp1_fabric_2 = (void *)0;


static int fabric_bind_bidi(Fabric *left, Fabric *right)
{
    if (!left || !right || !left->bridge || !right->bridge)
        return FABRIC_ERROR;
    if (fabric_bridge_bind_downstream(left->bridge, right) != FABRIC_SUCCESS)
        return FABRIC_ERROR;
    if (fabric_bridge_bind_downstream(right->bridge, left) != FABRIC_SUCCESS)
        return FABRIC_ERROR;
    return FABRIC_SUCCESS;
}

int fabric_init_all(void)
{
    int rc;

    g_comp1_fabric_1 = fabric_create();
    g_comp1_fabric_2 = fabric_create();
    if (!g_comp1_fabric_1 || !g_comp1_fabric_2)
        return FABRIC_ERROR;

    struct fabric_lib_binding {
        const char *lib_name;
        Fabric *fabric;
        int (*register_fn)(Fabric *);
    };

    struct fabric_lib_binding bindings[] = {
        { "flexos_core", g_comp1_fabric_1, register_flexos_core_functions },
        { "lwip", g_comp1_fabric_2, register_lwip_functions },
        { "nolibc", g_comp1_fabric_1, register_nolibc_functions },
        { "uklock", g_comp1_fabric_1, register_uklock_functions },
        { "ukmpi", g_comp1_fabric_1, register_ukmpi_functions },
        { "uknetdev", g_comp1_fabric_1, register_uknetdev_functions },
        { "uksched", g_comp1_fabric_2, register_uksched_functions },
        { "vfscore", g_comp1_fabric_1, register_vfscore_functions },
    };
    int binding_count = (int)(sizeof(bindings) / sizeof(bindings[0]));
    for (int i = 0; i < binding_count; i++) {
        rc = bindings[i].register_fn(bindings[i].fabric);
        if (rc != FABRIC_SUCCESS)
            return rc;
    }

    rc = fabric_bind_bidi(g_comp1_fabric_1, g_comp1_fabric_2);
    if (rc != FABRIC_SUCCESS)
        return rc;

    /* --- 隔离后端初始化 --- */
    {
        EPTConfig iso_cfg;
        iso_cfg.fabric_id = g_comp1_fabric_1->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_1->bridge, FABRIC_ISO_EPT, &iso_cfg);
        iso_cfg.fabric_id = g_comp1_fabric_2->fabric_id;
        fabric_bridge_set_isolation(g_comp1_fabric_2->bridge, FABRIC_ISO_EPT, &iso_cfg);
    }

    return FABRIC_SUCCESS;
}

extern int _liblwip_init(void);

/* Direct call: SKIP_FABRIC_SECTIONS (gate needs per-lib sections). */
static int __fabric_isolated_lwip_init(void)
{
    return _liblwip_init();
}
uk_lib_initcall_prio(__fabric_isolated_lwip_init, UK_PRIO_LATEST);

static int __fabric_lib_init(void)
{
    return fabric_init_all();
}
uk_lib_initcall_prio(__fabric_lib_init, UK_PRIO_EARLIEST);
