// Auto-generated by auto_register.py — do not edit

// Auto-generated for /root/.unikraft_akira/apps/redis/build/liblwip/origin/lwip-2.1.2/src/api/netdb.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, atoi, EL)
+ fabric_gate(1, atoi, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, atoi, EL)
+ fabric_gate_r(1, RET, atoi, EL)

// Auto-generated for /root/.unikraft_akira/apps/redis/build/libredis/origin/redis-5.0.6/deps/hiredis/net.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, getaddrinfo, EL)
+ fabric_gate(0, getaddrinfo, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, getaddrinfo, EL)
+ fabric_gate_r(0, RET, getaddrinfo, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, setsockopt, EL)
+ fabric_gate(0, setsockopt, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, setsockopt, EL)
+ fabric_gate_r(0, RET, setsockopt, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, socket, EL)
+ fabric_gate(0, socket, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, socket, EL)
+ fabric_gate_r(0, RET, socket, EL)

// Auto-generated for /root/.unikraft_akira/apps/redis/build/libredis/origin/redis-5.0.6/src/ae_select.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, select, EL)
+ fabric_gate(0, select, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, select, EL)
+ fabric_gate_r(0, RET, select, EL)

// Auto-generated for /root/.unikraft_akira/apps/redis/build/libredis/origin/redis-5.0.6/src/anet.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, accept, EL)
+ fabric_gate(0, accept, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, accept, EL)
+ fabric_gate_r(0, RET, accept, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, bind, EL)
+ fabric_gate(0, bind, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, bind, EL)
+ fabric_gate_r(0, RET, bind, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, freeaddrinfo, EL)
+ fabric_gate(0, freeaddrinfo, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, freeaddrinfo, EL)
+ fabric_gate_r(0, RET, freeaddrinfo, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, getaddrinfo, EL)
+ fabric_gate(0, getaddrinfo, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, getaddrinfo, EL)
+ fabric_gate_r(0, RET, getaddrinfo, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, getpeername, EL)
+ fabric_gate(0, getpeername, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, getpeername, EL)
+ fabric_gate_r(0, RET, getpeername, EL)

@noreturn_5@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, listen, EL)
+ fabric_gate(0, listen, EL)

@return_5@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, listen, EL)
+ fabric_gate_r(0, RET, listen, EL)

@noreturn_6@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, setsockopt, EL)
+ fabric_gate(0, setsockopt, EL)

@return_6@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, setsockopt, EL)
+ fabric_gate_r(0, RET, setsockopt, EL)

@noreturn_7@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, socket, EL)
+ fabric_gate(0, socket, EL)

@return_7@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, socket, EL)
+ fabric_gate_r(0, RET, socket, EL)

// Auto-generated for /root/.unikraft_akira/apps/redis/build/libredis/origin/redis-5.0.6/src/server.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, sendmsg, EL)
+ fabric_gate(0, sendmsg, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, sendmsg, EL)
+ fabric_gate_r(0, RET, sendmsg, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/init.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, printf, EL)
+ fabric_gate(1, printf, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, printf, EL)
+ fabric_gate_r(1, RET, printf, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_count, EL)
+ fabric_gate(1, uk_netdev_count, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_count, EL)
+ fabric_gate_r(1, RET, uk_netdev_count, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_get, EL)
+ fabric_gate(1, uk_netdev_get, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_get, EL)
+ fabric_gate_r(1, RET, uk_netdev_get, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_state_get, EL)
+ fabric_gate(1, uk_netdev_state_get, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_state_get, EL)
+ fabric_gate_r(1, RET, uk_netdev_state_get, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_semaphore_init, EL)
+ fabric_gate(1, uk_semaphore_init, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_semaphore_init, EL)
+ fabric_gate_r(1, RET, uk_semaphore_init, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/mailbox.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_create, EL)
+ fabric_gate(1, uk_mbox_create, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_create, EL)
+ fabric_gate_r(1, RET, uk_mbox_create, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_free, EL)
+ fabric_gate(1, uk_mbox_free, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_free, EL)
+ fabric_gate_r(1, RET, uk_mbox_free, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_post, EL)
+ fabric_gate(1, uk_mbox_post, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_post, EL)
+ fabric_gate_r(1, RET, uk_mbox_post, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_post_try, EL)
+ fabric_gate(1, uk_mbox_post_try, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_post_try, EL)
+ fabric_gate_r(1, RET, uk_mbox_post_try, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_recv, EL)
+ fabric_gate(1, uk_mbox_recv, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_recv, EL)
+ fabric_gate_r(1, RET, uk_mbox_recv, EL)

@noreturn_5@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_recv_to, EL)
+ fabric_gate(1, uk_mbox_recv_to, EL)

@return_5@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_recv_to, EL)
+ fabric_gate_r(1, RET, uk_mbox_recv_to, EL)

@noreturn_6@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mbox_recv_try, EL)
+ fabric_gate(1, uk_mbox_recv_try, EL)

@return_6@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mbox_recv_try, EL)
+ fabric_gate_r(1, RET, uk_mbox_recv_try, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/mutex.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_mutex_init, EL)
+ fabric_gate(1, uk_mutex_init, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_mutex_init, EL)
+ fabric_gate_r(1, RET, uk_mutex_init, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/netbuf.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netbuf_free_single, EL)
+ fabric_gate(1, uk_netbuf_free_single, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netbuf_free_single, EL)
+ fabric_gate_r(1, RET, uk_netbuf_free_single, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/semaphore.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_semaphore_init, EL)
+ fabric_gate(1, uk_semaphore_init, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_semaphore_init, EL)
+ fabric_gate_r(1, RET, uk_semaphore_init, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/sockets.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, dentry_alloc, EL)
+ fabric_gate(1, dentry_alloc, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, dentry_alloc, EL)
+ fabric_gate_r(1, RET, dentry_alloc, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, drele, EL)
+ fabric_gate(1, drele, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, drele, EL)
+ fabric_gate_r(1, RET, drele, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, vfscore_alloc_fd, EL)
+ fabric_gate(1, vfscore_alloc_fd, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, vfscore_alloc_fd, EL)
+ fabric_gate_r(1, RET, vfscore_alloc_fd, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, vfscore_install_fd, EL)
+ fabric_gate(1, vfscore_install_fd, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, vfscore_install_fd, EL)
+ fabric_gate_r(1, RET, vfscore_install_fd, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, vfscore_put_fd, EL)
+ fabric_gate(1, vfscore_put_fd, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, vfscore_put_fd, EL)
+ fabric_gate_r(1, RET, vfscore_put_fd, EL)

@noreturn_5@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, vfscore_put_file, EL)
+ fabric_gate(1, vfscore_put_file, EL)

@return_5@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, vfscore_put_file, EL)
+ fabric_gate_r(1, RET, vfscore_put_file, EL)

@noreturn_6@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, vfscore_vget, EL)
+ fabric_gate(1, vfscore_vget, EL)

@return_6@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, vfscore_vget, EL)
+ fabric_gate_r(1, RET, vfscore_vget, EL)

@noreturn_7@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, vrele, EL)
+ fabric_gate(1, vrele, EL)

@return_7@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, vrele, EL)
+ fabric_gate_r(1, RET, vrele, EL)

// Auto-generated for /root/.unikraft_akira/libs/lwip/uknetdev.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_configure, EL)
+ fabric_gate(1, uk_netdev_configure, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_configure, EL)
+ fabric_gate_r(1, RET, uk_netdev_configure, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_hwaddr_get, EL)
+ fabric_gate(1, uk_netdev_hwaddr_get, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_hwaddr_get, EL)
+ fabric_gate_r(1, RET, uk_netdev_hwaddr_get, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_info_get, EL)
+ fabric_gate(1, uk_netdev_info_get, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_info_get, EL)
+ fabric_gate_r(1, RET, uk_netdev_info_get, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_mtu_get, EL)
+ fabric_gate(1, uk_netdev_mtu_get, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_mtu_get, EL)
+ fabric_gate_r(1, RET, uk_netdev_mtu_get, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_rxq_configure, EL)
+ fabric_gate(1, uk_netdev_rxq_configure, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_rxq_configure, EL)
+ fabric_gate_r(1, RET, uk_netdev_rxq_configure, EL)

@noreturn_5@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_rxq_intr_enable, EL)
+ fabric_gate(1, uk_netdev_rxq_intr_enable, EL)

@return_5@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_rxq_intr_enable, EL)
+ fabric_gate_r(1, RET, uk_netdev_rxq_intr_enable, EL)

@noreturn_6@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_start, EL)
+ fabric_gate(1, uk_netdev_start, EL)

@return_6@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_start, EL)
+ fabric_gate_r(1, RET, uk_netdev_start, EL)

@noreturn_7@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_state_get, EL)
+ fabric_gate(1, uk_netdev_state_get, EL)

@return_7@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_state_get, EL)
+ fabric_gate_r(1, RET, uk_netdev_state_get, EL)

@noreturn_8@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_netdev_txq_configure, EL)
+ fabric_gate(1, uk_netdev_txq_configure, EL)

@return_8@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_netdev_txq_configure, EL)
+ fabric_gate_r(1, RET, uk_netdev_txq_configure, EL)

// Auto-generated for /root/.unikraft_akira/libs/pthread-embedded/attributes.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_get_prio, EL)
+ fabric_gate(0, uk_thread_get_prio, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_get_prio, EL)
+ fabric_gate_r(0, RET, uk_thread_get_prio, EL)

// Auto-generated for /root/.unikraft_akira/libs/pthread-embedded/pte_osal.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_exit, EL)
+ fabric_gate(0, uk_sched_thread_exit, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_exit, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_exit, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_sleep, EL)
+ fabric_gate(0, uk_sched_thread_sleep, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_sleep, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_sleep, EL)

@noreturn_2@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_get_prio, EL)
+ fabric_gate(0, uk_thread_get_prio, EL)

@return_2@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_get_prio, EL)
+ fabric_gate_r(0, RET, uk_thread_get_prio, EL)

@noreturn_3@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_inherit_signal_mask, EL)
+ fabric_gate(0, uk_thread_inherit_signal_mask, EL)

@return_3@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_inherit_signal_mask, EL)
+ fabric_gate_r(0, RET, uk_thread_inherit_signal_mask, EL)

@noreturn_4@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_set_prio, EL)
+ fabric_gate(0, uk_thread_set_prio, EL)

@return_4@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_set_prio, EL)
+ fabric_gate_r(0, RET, uk_thread_set_prio, EL)

@noreturn_5@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wait, EL)
+ fabric_gate(0, uk_thread_wait, EL)

@return_5@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wait, EL)
+ fabric_gate_r(0, RET, uk_thread_wait, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uk9p/9pdev.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uk9p/9preq.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uklock/include/uk/mutex.h

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uklock/include/uk/semaphore.h

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uknetdev/netdev.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_create, EL)
+ fabric_gate(0, uk_sched_thread_create, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_create, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_create, EL)

@noreturn_1@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wait, EL)
+ fabric_gate(0, uk_thread_wait, EL)

@return_1@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wait, EL)
+ fabric_gate_r(0, RET, uk_thread_wait, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uksched/sched.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, flexos_intelpku_mem_set_key, EL)
+ fabric_gate(1, flexos_intelpku_mem_set_key, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, flexos_intelpku_mem_set_key, EL)
+ fabric_gate_r(1, RET, flexos_intelpku_mem_set_key, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/uktime/time.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_sched_thread_sleep, EL)
+ fabric_gate(0, uk_sched_thread_sleep, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_sched_thread_sleep, EL)
+ fabric_gate_r(0, RET, uk_sched_thread_sleep, EL)

// Auto-generated for /root/.unikraft_akira/unikraft/lib/vfscore/pipe.c

@noreturn_0@
expression list EL;
expression COMP_FROM, COMP_TO;
@@
- flexos_nop_gate(COMP_FROM, COMP_TO, uk_thread_wake, EL)
+ fabric_gate(0, uk_thread_wake, EL)

@return_0@
expression list EL;
expression COMP_FROM, COMP_TO, RET;
@@
- flexos_nop_gate_r(COMP_FROM, COMP_TO, RET, uk_thread_wake, EL)
+ fabric_gate_r(0, RET, uk_thread_wake, EL)

// Disable direct uk_lib_initcall for fabric-isolated library
@disable_liblwip_init@
@@
-uk_lib_initcall(liblwip_init);
+/* fabric-isolated: liblwip_init invoked via fabric gate */
