/* Auto-generated by auto_register.py — do not edit */
#ifndef _FABRIC_INIT_H_
#define _FABRIC_INIT_H_

#include "../../../unikraft/lib/fabric-core/fabric/include/fabric.h"

extern Fabric *g_comp1_fabric_1;
extern Fabric *g_comp1_fabric_2;

int fabric_init_all(void);

#endif
