/* Auto-generated by auto_register.py — do not edit */
#ifndef _FABRIC_REGISTER_ALL_H_
#define _FABRIC_REGISTER_ALL_H_

#include "../../../unikraft/lib/fabric-core/include/fabric_error.h"
#include "../../../unikraft/lib/fabric-core/fabric/include/fabric.h"

typedef struct Fabric Fabric;
typedef void (*func_t)(void);
int fabric_register_function(Fabric *fabric, const char *func_name, func_t func_ptr);

int register_flexos_core_functions(Fabric *fabric);
int register_lwip_functions(Fabric *fabric);
int register_nolibc_functions(Fabric *fabric);
int register_uklock_functions(Fabric *fabric);
int register_ukmpi_functions(Fabric *fabric);
int register_uknetdev_functions(Fabric *fabric);
int register_uksched_functions(Fabric *fabric);
int register_vfscore_functions(Fabric *fabric);

#endif
