/* Auto-generated by auto_register.py — do not edit */
#include "fabric_register_all.h"
#include <uk/print.h>

extern const char __fsym_flexos_intelpku_mem_set_key[] __asm__("flexos_intelpku_mem_set_key") __attribute__((weak));
extern const char __fsym__liblwip_init[] __asm__("_liblwip_init") __attribute__((weak));
extern const char __fsym_accept[] __asm__("accept") __attribute__((weak));
extern const char __fsym_bind[] __asm__("bind") __attribute__((weak));
extern const char __fsym_freeaddrinfo[] __asm__("freeaddrinfo") __attribute__((weak));
extern const char __fsym_getaddrinfo[] __asm__("getaddrinfo") __attribute__((weak));
extern const char __fsym_getpeername[] __asm__("getpeername") __attribute__((weak));
extern const char __fsym_listen[] __asm__("listen") __attribute__((weak));
extern const char __fsym_select[] __asm__("select") __attribute__((weak));
extern const char __fsym_sendmsg[] __asm__("sendmsg") __attribute__((weak));
extern const char __fsym_setsockopt[] __asm__("setsockopt") __attribute__((weak));
extern const char __fsym_socket[] __asm__("socket") __attribute__((weak));
extern const char __fsym_atoi[] __asm__("atoi") __attribute__((weak));
extern const char __fsym_printf[] __asm__("printf") __attribute__((weak));
extern const char __fsym_uk_mutex_init[] __asm__("uk_mutex_init") __attribute__((weak));
extern const char __fsym_uk_semaphore_init[] __asm__("uk_semaphore_init") __attribute__((weak));
extern const char __fsym_uk_mbox_create[] __asm__("uk_mbox_create") __attribute__((weak));
extern const char __fsym_uk_mbox_free[] __asm__("uk_mbox_free") __attribute__((weak));
extern const char __fsym_uk_mbox_post[] __asm__("uk_mbox_post") __attribute__((weak));
extern const char __fsym_uk_mbox_post_try[] __asm__("uk_mbox_post_try") __attribute__((weak));
extern const char __fsym_uk_mbox_recv[] __asm__("uk_mbox_recv") __attribute__((weak));
extern const char __fsym_uk_mbox_recv_to[] __asm__("uk_mbox_recv_to") __attribute__((weak));
extern const char __fsym_uk_mbox_recv_try[] __asm__("uk_mbox_recv_try") __attribute__((weak));
extern const char __fsym_uk_netbuf_free_single[] __asm__("uk_netbuf_free_single") __attribute__((weak));
extern const char __fsym_uk_netdev_configure[] __asm__("uk_netdev_configure") __attribute__((weak));
extern const char __fsym_uk_netdev_count[] __asm__("uk_netdev_count") __attribute__((weak));
extern const char __fsym_uk_netdev_get[] __asm__("uk_netdev_get") __attribute__((weak));
extern const char __fsym_uk_netdev_hwaddr_get[] __asm__("uk_netdev_hwaddr_get") __attribute__((weak));
extern const char __fsym_uk_netdev_info_get[] __asm__("uk_netdev_info_get") __attribute__((weak));
extern const char __fsym_uk_netdev_mtu_get[] __asm__("uk_netdev_mtu_get") __attribute__((weak));
extern const char __fsym_uk_netdev_rxq_configure[] __asm__("uk_netdev_rxq_configure") __attribute__((weak));
extern const char __fsym_uk_netdev_rxq_intr_enable[] __asm__("uk_netdev_rxq_intr_enable") __attribute__((weak));
extern const char __fsym_uk_netdev_start[] __asm__("uk_netdev_start") __attribute__((weak));
extern const char __fsym_uk_netdev_state_get[] __asm__("uk_netdev_state_get") __attribute__((weak));
extern const char __fsym_uk_netdev_txq_configure[] __asm__("uk_netdev_txq_configure") __attribute__((weak));
extern const char __fsym_uk_sched_thread_create[] __asm__("uk_sched_thread_create") __attribute__((weak));
extern const char __fsym_uk_sched_thread_exit[] __asm__("uk_sched_thread_exit") __attribute__((weak));
extern const char __fsym_uk_sched_thread_sleep[] __asm__("uk_sched_thread_sleep") __attribute__((weak));
extern const char __fsym_uk_thread_get_prio[] __asm__("uk_thread_get_prio") __attribute__((weak));
extern const char __fsym_uk_thread_inherit_signal_mask[] __asm__("uk_thread_inherit_signal_mask") __attribute__((weak));
extern const char __fsym_uk_thread_set_prio[] __asm__("uk_thread_set_prio") __attribute__((weak));
extern const char __fsym_uk_thread_wait[] __asm__("uk_thread_wait") __attribute__((weak));
extern const char __fsym_uk_thread_wake[] __asm__("uk_thread_wake") __attribute__((weak));
extern const char __fsym_dentry_alloc[] __asm__("dentry_alloc") __attribute__((weak));
extern const char __fsym_drele[] __asm__("drele") __attribute__((weak));
extern const char __fsym_vfscore_alloc_fd[] __asm__("vfscore_alloc_fd") __attribute__((weak));
extern const char __fsym_vfscore_install_fd[] __asm__("vfscore_install_fd") __attribute__((weak));
extern const char __fsym_vfscore_put_fd[] __asm__("vfscore_put_fd") __attribute__((weak));
extern const char __fsym_vfscore_put_file[] __asm__("vfscore_put_file") __attribute__((weak));
extern const char __fsym_vfscore_vget[] __asm__("vfscore_vget") __attribute__((weak));
extern const char __fsym_vrele[] __asm__("vrele") __attribute__((weak));

int register_flexos_core_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_flexos_intelpku_mem_set_key == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: flexos_intelpku_mem_set_key (flexos_core)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "flexos_intelpku_mem_set_key", (func_t)(void *)__fsym_flexos_intelpku_mem_set_key);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] flexos_core: %d registered, %d missing, 1 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_lwip_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym__liblwip_init == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: _liblwip_init (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "_liblwip_init", (func_t)(void *)__fsym__liblwip_init);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_accept == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: accept (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "accept", (func_t)(void *)__fsym_accept);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_bind == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: bind (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "bind", (func_t)(void *)__fsym_bind);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_freeaddrinfo == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: freeaddrinfo (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "freeaddrinfo", (func_t)(void *)__fsym_freeaddrinfo);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_getaddrinfo == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: getaddrinfo (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "getaddrinfo", (func_t)(void *)__fsym_getaddrinfo);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_getpeername == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: getpeername (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "getpeername", (func_t)(void *)__fsym_getpeername);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_listen == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: listen (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "listen", (func_t)(void *)__fsym_listen);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_select == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: select (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "select", (func_t)(void *)__fsym_select);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_sendmsg == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: sendmsg (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "sendmsg", (func_t)(void *)__fsym_sendmsg);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_setsockopt == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: setsockopt (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "setsockopt", (func_t)(void *)__fsym_setsockopt);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_socket == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: socket (lwip)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "socket", (func_t)(void *)__fsym_socket);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] lwip: %d registered, %d missing, 11 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_nolibc_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_atoi == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: atoi (nolibc)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "atoi", (func_t)(void *)__fsym_atoi);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_printf == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: printf (nolibc)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "printf", (func_t)(void *)__fsym_printf);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] nolibc: %d registered, %d missing, 2 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_uklock_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_uk_mutex_init == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mutex_init (uklock)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mutex_init", (func_t)(void *)__fsym_uk_mutex_init);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_semaphore_init == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_semaphore_init (uklock)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_semaphore_init", (func_t)(void *)__fsym_uk_semaphore_init);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] uklock: %d registered, %d missing, 2 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_ukmpi_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_uk_mbox_create == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_create (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_create", (func_t)(void *)__fsym_uk_mbox_create);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_mbox_free == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_free (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_free", (func_t)(void *)__fsym_uk_mbox_free);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_mbox_post == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_post (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_post", (func_t)(void *)__fsym_uk_mbox_post);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_mbox_post_try == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_post_try (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_post_try", (func_t)(void *)__fsym_uk_mbox_post_try);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_mbox_recv == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_recv (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_recv", (func_t)(void *)__fsym_uk_mbox_recv);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_mbox_recv_to == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_recv_to (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_recv_to", (func_t)(void *)__fsym_uk_mbox_recv_to);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_mbox_recv_try == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_mbox_recv_try (ukmpi)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_mbox_recv_try", (func_t)(void *)__fsym_uk_mbox_recv_try);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] ukmpi: %d registered, %d missing, 7 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_uknetdev_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_uk_netbuf_free_single == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netbuf_free_single (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netbuf_free_single", (func_t)(void *)__fsym_uk_netbuf_free_single);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_configure == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_configure (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_configure", (func_t)(void *)__fsym_uk_netdev_configure);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_count == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_count (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_count", (func_t)(void *)__fsym_uk_netdev_count);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_get == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_get (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_get", (func_t)(void *)__fsym_uk_netdev_get);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_hwaddr_get == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_hwaddr_get (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_hwaddr_get", (func_t)(void *)__fsym_uk_netdev_hwaddr_get);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_info_get == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_info_get (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_info_get", (func_t)(void *)__fsym_uk_netdev_info_get);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_mtu_get == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_mtu_get (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_mtu_get", (func_t)(void *)__fsym_uk_netdev_mtu_get);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_rxq_configure == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_rxq_configure (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_rxq_configure", (func_t)(void *)__fsym_uk_netdev_rxq_configure);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_rxq_intr_enable == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_rxq_intr_enable (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_rxq_intr_enable", (func_t)(void *)__fsym_uk_netdev_rxq_intr_enable);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_start == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_start (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_start", (func_t)(void *)__fsym_uk_netdev_start);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_state_get == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_state_get (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_state_get", (func_t)(void *)__fsym_uk_netdev_state_get);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_netdev_txq_configure == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_netdev_txq_configure (uknetdev)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_netdev_txq_configure", (func_t)(void *)__fsym_uk_netdev_txq_configure);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] uknetdev: %d registered, %d missing, 12 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_uksched_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_uk_sched_thread_create == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_sched_thread_create (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_sched_thread_create", (func_t)(void *)__fsym_uk_sched_thread_create);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_sched_thread_exit == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_sched_thread_exit (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_sched_thread_exit", (func_t)(void *)__fsym_uk_sched_thread_exit);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_sched_thread_sleep == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_sched_thread_sleep (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_sched_thread_sleep", (func_t)(void *)__fsym_uk_sched_thread_sleep);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_get_prio == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_get_prio (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_get_prio", (func_t)(void *)__fsym_uk_thread_get_prio);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_inherit_signal_mask == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_inherit_signal_mask (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_inherit_signal_mask", (func_t)(void *)__fsym_uk_thread_inherit_signal_mask);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_set_prio == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_set_prio (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_set_prio", (func_t)(void *)__fsym_uk_thread_set_prio);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_wait == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_wait (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_wait", (func_t)(void *)__fsym_uk_thread_wait);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_uk_thread_wake == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: uk_thread_wake (uksched)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "uk_thread_wake", (func_t)(void *)__fsym_uk_thread_wake);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] uksched: %d registered, %d missing, 8 total\n", registered, missing);
    return FABRIC_SUCCESS;
}

int register_vfscore_functions(Fabric *fabric)
{
    int rc;
    int registered = 0;
    int missing = 0;
    if (__fsym_dentry_alloc == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: dentry_alloc (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "dentry_alloc", (func_t)(void *)__fsym_dentry_alloc);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_drele == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: drele (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "drele", (func_t)(void *)__fsym_drele);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_vfscore_alloc_fd == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: vfscore_alloc_fd (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "vfscore_alloc_fd", (func_t)(void *)__fsym_vfscore_alloc_fd);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_vfscore_install_fd == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: vfscore_install_fd (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "vfscore_install_fd", (func_t)(void *)__fsym_vfscore_install_fd);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_vfscore_put_fd == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: vfscore_put_fd (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "vfscore_put_fd", (func_t)(void *)__fsym_vfscore_put_fd);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_vfscore_put_file == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: vfscore_put_file (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "vfscore_put_file", (func_t)(void *)__fsym_vfscore_put_file);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_vfscore_vget == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: vfscore_vget (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "vfscore_vget", (func_t)(void *)__fsym_vfscore_vget);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    if (__fsym_vrele == (const char *)0) {
        uk_pr_info("[fabric-register] skip unresolved: vrele (vfscore)\n");
        missing++;
    } else {
        rc = fabric_register_function(fabric, "vrele", (func_t)(void *)__fsym_vrele);
        if (rc != FABRIC_SUCCESS)
            return rc;
        registered++;
    }
    uk_pr_info("[fabric-register] vfscore: %d registered, %d missing, 8 total\n", registered, missing);
    return FABRIC_SUCCESS;
}
